[package]
name = "photo"
version = "0.7.0"
authors = ["vabyz971 <vabyz971@gmail.com>"]
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
eframe.workspace = true
egui.workspace = true
egui_dock.workspace = true
serde.workspace = true
serde_json.workspace = true
ui-kit = { path = "../../packages/ui-kit" }
photo-engine = { path = "../../engines/photo-engine" }
uuid.workspace = true
image.workspace = true
