[package]
name = "photo-engine"
version = "0.7.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
datatypes = { path = "../../core/datatypes" }
math-utils = { path = "../../packages/math-utils" }
render-graph = { path = "../../core/render-graph" }
tiles = { path = "../../core/tiles" }
image = { workspace = true }
rayon = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
base64.workspace = true
uuid = { workspace = true }
